name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: "./.github/workflows/test.yaml"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: DockerCIPracticeUdemy
          environment_name: Dockercipracticeudemy-env
          existing_bucket_name: elasticbeanstalk-us-east-1-751999054816
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

