name: Test Frontend
on:
  pull_request:
    branches:
      - main
  workflow-call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t gafalcon/docker-ci-practice -f Dockerfile.dev .
      - run: docker run -e CI=true gafalcon/docker-ci-practice npm test
